const requests = {
  trending: [
    'Guardians of the Galaxy Vol. 2',
    'Spider-Man: No Way Home',
    'Avengers: Endgame',
    'Inception',
    'The Dark Knight',
    'Interstellar',
    'The Avengers',
    'Captain America: Civil War',
    'Black Panther',
    'Iron Man',
    'Thor: Ragnarok',
    'Doctor Strange',
    'Avatar',
    'Jurassic World',
    'Fast & Furious 7',
  ],
  
  netflixOriginals: [
    'Extraction',
    'The Irishman',
    'Bird Box',
    'Bright',
    '6 Underground',
    'The Old Guard',
    'Red Notice',
    'Don\'t Look Up',
    'The Platform',
    'The Trial of the Chicago 7',
    'Tick, Tick... Boom!',
    'Glass Onion',
    'The Gray Man',
    'The Adam Project',
    'Uncut Gems',
  ],
  
  topRated: [
    'The Shawshank Redemption',
    'The Godfather',
    'Pulp Fiction',
    'The Dark Knight',
    'Fight Club',
    'Schindler\'s List',
    '12 Angry Men',
    'The Godfather Part II',
    'Goodfellas',
    'Forrest Gump',
    'Gladiator',
    'Titanic',
    'The Lord of the Rings: The Return of the King',
    'Shutter Island',
    'The Prestige',
  ],
  
  actionMovies: [
    'Die Hard',
    'The Matrix',
    'Mad Max: Fury Road',
    'John Wick',
    'Mission: Impossible',
    'John Wick: Chapter 2',
    'John Wick: Chapter 3',
    'Mad Max: Fury Road',
    'The Bourne Identity',
    'Taken',
    '300',
    'Kill Bill',
    'Gladiator',
    'Braveheart',
    'Terminator 2',
    'Predator',
    'Alien',
    'Aliens',
    'Blade Runner',
    'Edge of Tomorrow',
  ],
  
  comedyMovies: [
    'Superbad',
    'The Hangover',
    'Anchorman',
    'Borat',
    'Zombieland',
    'Step Brothers',
    'Talladega Nights',
    'Wedding Crashers',
    'DodgeBall',
    'Old School',
    '21 Jump Street',
    '22 Jump Street',
    'Neighbors',
    'Tropic Thunder',
    'Forgetting Sarah Marshall',
    'Pineapple Express',
    'Knocked Up',
    'The 40-Year-Old Virgin',
    'Shaun of the Dead',
    'Scott Pilgrim vs. the World',
  ],
  
  horrorMovies: [
    'The Shining',
    'Get Out',
    'Hereditary',
    'The Conjuring',
    'Halloween',
    'The Exorcist',
    'Psycho',
    'The Thing',
    'Alien',
    'Aliens',
    'Evil Dead',
    'The Cabin in the Woods',
    'A Quiet Place',
    'The Witch',
    'It Follows',
    'Sinister',
    'Insidious',
    'Paranormal Activity',
    'Scream',
    'The Silence of the Lambs',
  ],
  
  romanceMovies: [
    'The Notebook',
    'Titanic',
    'Pride and Prejudice',
    'Before Sunrise',
    'La La Land',
    '500 Days of Summer',
    'Eternal Sunshine of the Spotless Mind',
    'About Time',
    'The Fault in Our Stars',
    'Crazy Stupid Love',
    'Silver Linings Playbook',
    'The Vow',
    'Me Before You',
    'Call Me by Your Name',
    'Before Sunset',
    'When Harry Met Sally',
    'Casablanca',
    'The Princess Bride',
    '10 Things I Hate About You',
    'The Proposal',
  ],
  
  documentaries: [
    'Free Solo',
    'The Social Dilemma',
    'Jiro Dreams of Sushi',
    'Won\'t You Be My Neighbor?',
    'Amy',
    'Man on Wire',
    'Bowling for Columbine',
    'March of the Penguins',
    'The Cove',
    'An Inconvenient Truth',
    'Food, Inc.',
    'Blackfish',
    'Exit Through the Gift Shop',
    'Super Size Me',
    'The Act of Killing',
  ],
  
  topRatedTV: [
    'Game of Thrones',
    'Breaking Bad',
    'The Office',
    'Stranger Things',
    'The Crown',
    'The Sopranos',
    'The Wire',
    'Lost',
    'True Detective',
    'Sherlock',
    'True Detective',
    'Westworld',
    'House of Cards',
    'Orange Is the New Black',
    'Narcos',
    'Money Heist',
    'Dark',
    'Black Mirror',
    'The Boys',
    'The Last of Us',
    'Better Call Saul',
    'Prison Break',
    'The Walking Dead',
    'Dexter',
    'Mad Men',
  ],
}

export default requests

